DROP TABLE IF EXISTS `meals`;
CREATE TABLE `meals` (
  id int(11) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  strMeal varchar(25) NOT NULL,
  strCategory varchar(25) NOT NULL,
  strArea varchar(25) NOT NULL,
  strInstructions varchar(255) NOT NULL,
  strMealThumb varchar(255) NOT NULL,
  strTags varchar(25) NOT NULL,
  strYoutube varchar(255) NOT NULL,
  strIngredient1 varchar(25) NOT NULL,
  strIngredient2 varchar(25) NOT NULL,
  strIngredient3 varchar(25) NOT NULL,
  strIngredient4 varchar(25) NOT NULL,
  strIngredient5 varchar(25) NOT NULL,
  strIngredient6 varchar(25) NOT NULL,
  strIngredient7 varchar(25) NOT NULL,
  strIngredient8 varchar(25) NOT NULL,
  strIngredient9 varchar(25) NOT NULL,
  strIngredient10 varchar(25) NOT NULL,
  strIngredient11 varchar(25) NOT NULL,
  strIngredient12 varchar(25) NOT NULL,
  strIngredient13 varchar(25) NOT NULL,
  strIngredient14 varchar(25) NOT NULL,
  strIngredient15 varchar(25) NOT NULL,
  strIngredient16 varchar(25) NOT NULL,
  strIngredient17 varchar(25) NOT NULL,
  strIngredient18 varchar(25) NOT NULL,
  strIngredient19 varchar(25) NOT NULL,
  strIngredient20 varchar(25) NOT NULL,
  strMeasure1 varchar(25) NOT NULL,
  strMeasure2 varchar(25) NOT NULL,
  strMeasure3 varchar(25) NOT NULL,
  strMeasure4 varchar(25) NOT NULL,
  strMeasure5 varchar(25) NOT NULL,
  strMeasure6 varchar(25) NOT NULL,
  strMeasure7 varchar(25) NOT NULL,
  strMeasure8 varchar(25) NOT NULL,
  strMeasure9 varchar(25) NOT NULL,
  strMeasure10 varchar(25) NOT NULL,
  strMeasure11 varchar(25) NOT NULL,
  strMeasure12 varchar(25) NOT NULL,
  strMeasure13 varchar(25) NOT NULL,
  strMeasure14 varchar(25) NOT NULL,
  strMeasure15 varchar(25) NOT NULL,
  strMeasure16 varchar(25) NOT NULL,
  strMeasure17 varchar(25) NOT NULL,
  strMeasure18 varchar(25) NOT NULL,
  strMeasure19 varchar(25) NOT NULL,
  strMeasure20 varchar(25) NOT NULL,
  strSource varchar(255) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
INSERT INTO `meals` (
    `id`,
    `strMeal`,
    `strCategory`,
    `strArea`,
    `strInstructions`,
    `strMealThumb`,
    `strTags`,
    `strYoutube`,
    `strIngredient1`,
    `strIngredient2`,
    `strIngredient3`,
    `strIngredient4`,
    `strIngredient5`,
    `strIngredient6`,
    `strIngredient7`,
    `strIngredient8`,
    `strIngredient9`,
    `strIngredient10`,
    `strIngredient11`,
    `strIngredient12`,
    `strIngredient13`,
    `strIngredient14`,
    `strIngredient15`,
    `strIngredient16`,
    `strIngredient17`,
    `strIngredient18`,
    `strIngredient19`,
    `strIngredient20`,
    `strMeasure1`,
    `strMeasure2`,
    `strMeasure3`,
    `strMeasure4`,
    `strMeasure5`,
    `strMeasure6`,
    `strMeasure7`,
    `strMeasure8`,
    `strMeasure9`,
    `strMeasure10`,
    `strMeasure11`,
    `strMeasure12`,
    `strMeasure13`,
    `strMeasure14`,
    `strMeasure15`,
    `strMeasure16`,
    `strMeasure17`,
    `strMeasure18`,
    `strMeasure19`,
    `strMeasure20`,
    `strSource`
  )
VALUES ('52977'),
  ('Corba'),
  ('Side'),
  ('Turkish'),
  (
    "Pick through your lentils for any foreign debris, rinse them 2 or 3 times, drain, and set aside.  Fair warning, this will probably turn your lentils into a solid block that you’ll have to break up later
In a large pot over medium-high heat, sauté the olive oil and the onion with a pinch of salt for about 3 minutes, then add the carrots and cook for another 3 minutes.
Add the tomato paste and stir it around for around 1 minute. Now add the cumin, paprika, mint, thyme, black pepper, and red pepper as quickly as you can and stir for 10 seconds to bloom the spices. Congratulate yourself on how amazing your house now smells.
Immediately add the lentils, water, broth, and salt. Bring the soup to a (gentle) boil.
After it has come to a boil, reduce heat to medium-low, cover the pot halfway, and cook for 15-20 minutes or until the lentils have fallen apart and the carrots are completely cooked.
After the soup has cooked and the lentils are tender, blend the soup either in a blender or simply use a hand blender to reach the consistency you desire. Taste for seasoning and add more salt if necessary.
Serve with crushed-up crackers, torn up bread, or something else to add some extra thickness.  You could also use a traditional thickener (like cornstarch or flour), but I prefer to add crackers for some texture and saltiness.  Makes great leftovers, stays good in the fridge for about a week."
  ),
  (
    "https://www.themealdb.com/images/media/meals/58oia61564916529.jpg"
  ),
  ('Soup'),
  ("https://www.youtube.com/watch?v=VVnZd8A84z4"),
  ("Lentils"),
  ("Onion"),
  ("Carrots"),
  ("Tomato Puree"),
  ("Cumin"),
  ("Paprika"),
  ("Mint"),
  ("Thyme"),
  ("Black Pepper"),
  ("Red Pepper Flakes"),
  ("Vegetable Stock"),
  ("Water"),
  ("Sea Salt"),
  (" "),
  (" "),
  (" "),
  (" "),
  (" "),
  (" "),
  (" "),
  ("1 cup "),
  ("1 large"),
  ("1 large"),
  ("1 tbs"),
  ("2 tsp"),
  ("1 tsp "),
  ("1/2 tsp"),
  ("1/2 tsp"),
  ("1/4 tsp"),
  ("1/4 tsp"),
  ("4 cups "),
  ("1 cup "),
  ("Pinch"),
  (" "),
  (" "),
  (" "),
  (" "),
  (" "),
  (" "),
  (" "),
  (
    "https://findingtimeforcooking.com/main-dishes/red-lentil-soup-corba/"
  );
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  id int(11) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  image varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  password varchar(255) NOT NULL
);
ENGINE = InnoDB DEFAULT CHARSET = utf8;
INSERT INTO `users` (
    `id`,
    `name`,
    `image`,
    `email`,
    `password`
  )
VALUES ('1'),
  ('Adnan'),
  ("http://bit.ly/3RBkTRn"),
  ('adnan@email.com'),
  ('aaaaaa'),
  ('2'),
  ('Alexis'),
  ("http://bit.ly/3RxZ31g"),
  ('alexis@email.com'),
  ('bbbbbb'),
  ('3'),
  ('Benoit'),
  ("https://bit.ly/3wXWMTO"),
  ('benoit@email.com'),
  ('cccccc'),
  ('4'),
  ('Charlotte'),
  ("http://bit.ly/3Y4iQI1"),
  ('charlotte@email.com'),
  ('dddddd'),
  ('5'),
  ('Edouard'),
  ("http://bit.ly/3wVl3tF"),
  ('edouard@email.com'),
  ('eeeeee'),
  ('6'),
  ('Farid'),
  ("http://bit.ly/3YrEyWs"),
  ('andrea'),
  ('ffffff'),
  ('7'),
  ('Fred'),
  ("http://bit.ly/3Ry0zR0"),
  ('fred@email.com'),
  ('gggggg'),
  ('8'),
  ('Heri'),
  ("http://bit.ly/3YrETZe"),
  ('Heri@email.com'),
  ('hhhhhh'),
  ('9'),
  ('Jessy'),
  ("http://bit.ly/3x0iOVY"),
  ('Jessy@email.com'),
  ('iiiiii'),
  ('10'),
  ('Justine'),
  ("http://bit.ly/3RzqgAI"),
  ('Justine@email.com'),
  ('jjjjjj'),
  ('11'),
  ('Louen'),
  ("http://bit.ly/40wDp1n"),
  ('louen@email.com'),
  ('kkkkkk'),
  ('12'),
  ('Mounir'),
  ("http://bit.ly/3JIMSg5"),
  ('mounir@email.com'),
  ('llllll'),
  ('13'),
  ('Lucie'),
  ("http://bit.ly/3HWEYP8"),
  ('lucie@email.com'),
  ('mmmmmm'),
  ('14'),
  ('Olivier L'),
  ("http://bit.ly/3JHMoa4"),
  ('olivier@email.com'),
  ('nnnnnn'),
  ('15'),
  ('Olivier N'),
  ("http://bit.ly/3X1iXml"),
  ('oliviern@email.com'),
  ('oooooo'),
  ('16'),
  ('Pierre Yves'),
  ("http://bit.ly/3jzUpmW"),
  ('pierreyves@email.com'),
  ('pppppp'),
  ('17'),
  ('Valentin'),
  ("http://bit.ly/3ldiD6J"),
  ('valentin@email.com'),
  ('qqqqqq'),
  ('18'),
  ('Rémi'),
  ("http://bit.ly/3HYE1Wi"),
  ('remi@email.com'),
  ('rrrrrr'),
  ('19'),
  ('José'),
  ("http://bit.ly/3I0AhE3"),
  ('jose@email.com'),
  ('ssssss'),
  ('20'),
  ('Robin'),
  ("http://bit.ly/3leMYSr"),
  ('robin@email.com'),
  ('tttttt'),
  ('21'),
  ('Rohan'),
  ("http://bit.ly/3RBDe0E"),
  ('rohan@email.com'),
  ('uuuuuu'),
  ('22'),
  ('Romain B'),
  ("http://bit.ly/3HB5L27"),
  ('romain@email.com'),
  ('vvvvvv'),
  ('23'),
  ('Romain G'),
  ("http://bit.ly/3lcUopt"),
  ('romain@email.com'),
  ('wwwwww'),
  ('24'),
  ('Simon'),
  ("http://bit.ly/3YoKpLV"),
  ('simon@email.com'),
  ('xxxxxx'),
  ('25'),
  ('Valentin'),
  ("http://bit.ly/3ldiD6J"),
  ('valentin@email.com'),
  ('yyyyyy'),
  ('26'),
  ('Classe'),
  ("http://bit.ly/3ldiD6J"),
  ('wild@email.com'),
  ('zzzzzz');
DROP TABLE IF EXISTS `users_meals`;
CREATE TABLE `users_meals` (
  id int(11) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  users_id int(11) UNSIGNED NOT NULL,
  meals_id int(11) UNSIGNED NOT NULL,
  FOREIGN KEY (users_id) REFERENCES users(id),
  FOREIGN KEY (meals_id) REFERENCES meals(id)
);
ENGINE = InnoDB DEFAULT CHARSET = utf8;